"""
Tests for app.py business logic — exercises all helpers that don't require a running Streamlit server.
Imports are done inside each test to avoid triggering st.set_page_config at collection time.
"""

from __future__ import annotations

from pathlib import Path
import json

import pandas as pd
import pytest

CONFIG_DIR = Path(__file__).parent.parent / "config"
PORTFOLIO_PATH = Path(__file__).parent.parent / "output" / "portfolio_state.json"

# ── Fixtures ──────────────────────────────────────────────────────────────────

@pytest.fixture(scope="module")
def portfolio_state():
    """Real portfolio_state.json generated by ETL from test fixtures."""
    if PORTFOLIO_PATH.exists():
        data = json.loads(PORTFOLIO_PATH.read_text())
        if data.get("accounts"):   # only use real file when it has actual data
            return data
    # Minimal synthetic state if ETL hasn't been run yet
    return {
        "schema_version": "1.0",
        "generated_at": "2026-05-05T00:00:00+00:00",
        "owner": {"household_id": "hh-001", "members": [
            {"id": "m1", "name": "Primary", "birth_date": "1975-01-01", "role": "primary"},
        ]},
        "accounts": [
            {"id": "acc-taxable", "institution": "Test", "adapter_id": "x",
             "account_type": "brokerage", "tax_treatment": "taxable",
             "owner_id": "m1", "as_of_date": "2026-05-05", "balance_usd": 400_000,
             "holdings": [{"ticker_or_name": "VTI", "asset_class": "us_equity",
                           "value_usd": 400_000, "cost_basis_usd": 250_000}]},
            {"id": "acc-deferred", "institution": "Test", "adapter_id": "x",
             "account_type": "401k", "tax_treatment": "tax_deferred",
             "owner_id": "m1", "as_of_date": "2026-05-05", "balance_usd": 800_000,
             "holdings": [{"ticker_or_name": "VIIIX", "asset_class": "us_equity",
                           "value_usd": 800_000}]},
            {"id": "acc-roth", "institution": "Test", "adapter_id": "x",
             "account_type": "roth_ira", "tax_treatment": "tax_free",
             "owner_id": "m1", "as_of_date": "2026-05-05", "balance_usd": 200_000,
             "holdings": [{"ticker_or_name": "FZROX", "asset_class": "us_equity",
                           "value_usd": 200_000}]},
        ],
        "summary": {
            "total_net_worth_usd": 1_400_000,
            "by_tax_treatment": {"taxable": 400_000, "tax_deferred": 800_000, "tax_free": 200_000},
            "by_asset_class": {"us_equity": 1_400_000},
        },
    }


@pytest.fixture
def default_cash_flows():
    return pd.DataFrame([
        {"Name": "Core Living Expenses",      "Category": "Essential",     "Annual ($)": 60_000, "Active": True},
        {"Name": "Property Tax & Insurance",  "Category": "Essential",     "Annual ($)": 8_000,  "Active": True},
        {"Name": "Travel",                    "Category": "Discretionary", "Annual ($)": 12_000, "Active": True},
        {"Name": "Social Security (Primary)", "Category": "Income",        "Annual ($)": 28_000, "Active": False},
    ])


@pytest.fixture
def default_sim_params():
    return {
        "mean_annual_return": 7.0,
        "return_std_dev": 15.0,
        "inflation_rate": 3.0,
        "plan_to_age": 90,
        "num_iterations": 100,
        "social_security_start_age": 67,
        "filing_status": "married_filing_jointly",
        "household_size": 2,
    }


# ── Cash flow aggregation logic ───────────────────────────────────────────────

class TestCashFlowAggregation:
    def _aggregate(self, cf: pd.DataFrame):
        active = cf[cf["Active"]]
        expenses = float(active[active["Category"] != "Income"]["Annual ($)"].sum())
        income   = float(active[active["Category"] == "Income"]["Annual ($)"].sum())
        return expenses, income

    def test_only_active_rows_counted(self, default_cash_flows):
        expenses, income = self._aggregate(default_cash_flows)
        assert expenses == 80_000   # 60k + 8k + 12k
        assert income == 0.0        # SS row is inactive

    def test_toggle_ss_on_changes_income(self, default_cash_flows):
        cf = default_cash_flows.copy()
        cf.loc[cf["Name"].str.contains("Social Security"), "Active"] = True
        expenses, income = self._aggregate(cf)
        assert income == 28_000

    def test_net_equals_expenses_minus_income(self, default_cash_flows):
        expenses, income = self._aggregate(default_cash_flows)
        net = expenses - income
        assert net == expenses  # income inactive

    def test_all_inactive_returns_zeros(self, default_cash_flows):
        cf = default_cash_flows.copy()
        cf["Active"] = False
        expenses, income = self._aggregate(cf)
        assert expenses == 0.0
        assert income == 0.0

    def test_discretionary_counted_as_expense(self, default_cash_flows):
        # "Travel" is Discretionary, not Income — should be in expenses
        active = default_cash_flows[default_cash_flows["Active"]]
        travel_rows = active[active["Name"] == "Travel"]
        assert len(travel_rows) == 1
        expenses, _ = self._aggregate(default_cash_flows)
        assert expenses >= 12_000


# ── SimulationParams construction from portfolio + overrides ──────────────────

class TestBuildSimParams:
    def _build(self, ps, cf, sp):
        """Mirrors the _build_sim_params() logic in app.py."""
        from engine import SimulationParams
        active = cf[cf["Active"]]
        expenses = float(active[active["Category"] != "Income"]["Annual ($)"].sum())
        income   = float(active[active["Category"] == "Income"]["Annual ($)"].sum())
        return SimulationParams.from_portfolio_state(
            ps,
            overrides={
                "annual_spending_today":     expenses,
                "social_security_annual":    income,
                "social_security_start_age": int(sp["social_security_start_age"]),
                "mean_annual_return":        sp["mean_annual_return"] / 100.0,
                "return_std_dev":            sp["return_std_dev"] / 100.0,
                "inflation_rate":            sp["inflation_rate"] / 100.0,
                "plan_to_age":               int(sp["plan_to_age"]),
                "num_iterations":            int(sp["num_iterations"]),
                "filing_status":             sp["filing_status"],
                "household_size":            int(sp["household_size"]),
            },
        )

    def test_spending_from_cash_flows(self, portfolio_state, default_cash_flows, default_sim_params):
        p = self._build(portfolio_state, default_cash_flows, default_sim_params)
        assert p.annual_spending_today == 80_000

    def test_return_percentage_converted_to_decimal(self, portfolio_state, default_cash_flows, default_sim_params):
        p = self._build(portfolio_state, default_cash_flows, default_sim_params)
        assert p.mean_annual_return == pytest.approx(0.07)
        assert p.return_std_dev     == pytest.approx(0.15)
        assert p.inflation_rate     == pytest.approx(0.03)

    def test_taxable_basis_populated_from_holdings(self, portfolio_state, default_cash_flows, default_sim_params):
        p = self._build(portfolio_state, default_cash_flows, default_sim_params)
        assert p.taxable_basis > 0

    def test_bucket_totals_match_portfolio_summary(self, portfolio_state, default_cash_flows, default_sim_params):
        from engine import SimulationParams
        p = self._build(portfolio_state, default_cash_flows, default_sim_params)
        by_tt = portfolio_state["summary"]["by_tax_treatment"]
        assert p.taxable_balance       == by_tt["taxable"]
        assert p.tax_deferred_balance  == by_tt["tax_deferred"]
        assert p.tax_free_balance      == by_tt["tax_free"]

    def test_ss_income_becomes_param(self, portfolio_state, default_cash_flows, default_sim_params):
        cf = default_cash_flows.copy()
        cf.loc[cf["Name"].str.contains("Social Security"), "Active"] = True
        p = self._build(portfolio_state, cf, default_sim_params)
        assert p.social_security_annual == 28_000


# ── Chart helpers (no Streamlit required) ─────────────────────────────────────

class TestChartHelpers:
    def _trajectory_chart(self, result):
        """Inline copy of _trajectory_chart() from app.py to test without st."""
        import plotly.graph_objects as go
        ages = result["ages"]
        med  = result["median_trajectory"]
        p10  = result["p10_trajectory"]
        p90  = result["p90_trajectory"]

        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=ages + ages[::-1], y=p90 + p10[::-1],
            fill="toself", fillcolor="rgba(59,130,246,0.12)",
            line=dict(color="rgba(0,0,0,0)"), name="band",
        ))
        fig.add_trace(go.Scatter(x=ages, y=p10, name="p10"))
        fig.add_trace(go.Scatter(x=ages, y=p90, name="p90"))
        fig.add_trace(go.Scatter(x=ages, y=med, name="Median"))
        return fig

    def _make_result(self, n=41):
        ages = list(range(50, 50 + n))
        return {
            "ages": ages,
            "median_trajectory":  [1_500_000 - i * 10_000 for i in range(n)],
            "p10_trajectory":     [1_000_000 - i * 15_000 for i in range(n)],
            "p90_trajectory":     [2_200_000 + i * 5_000  for i in range(n)],
            "median_taxes":       [8_000.0] * n,
            "median_healthcare":  [5_000.0] * n,
            "success_rate": 0.85,
        }

    def test_trajectory_chart_has_four_traces(self):
        result = self._make_result()
        fig = self._trajectory_chart(result)
        assert len(fig.data) == 4

    def test_band_polygon_length_correct(self):
        result = self._make_result(41)
        fig = self._trajectory_chart(result)
        band = fig.data[0]
        assert len(band.x) == 41 * 2   # forward + backward ages
        assert len(band.y) == 41 * 2

    def test_median_line_length_matches_ages(self):
        result = self._make_result(41)
        fig = self._trajectory_chart(result)
        median_trace = fig.data[3]
        assert len(median_trace.x) == 41
        assert len(median_trace.y) == 41

    def test_aca_cliff_detection(self):
        """ACA cliff logic: max jump > $5k in healthcare trajectory."""
        hc = [3_000.0] * 10 + [22_000.0] + [22_000.0] * 5  # jump at index 10
        max_jump = max(abs(hc[i] - hc[i - 1]) for i in range(1, len(hc)))
        assert max_jump > 5_000

    def test_no_aca_cliff_when_smooth(self):
        hc = [5_000.0 + i * 50 for i in range(20)]  # gradual increase
        max_jump = max(abs(hc[i] - hc[i - 1]) for i in range(1, len(hc)))
        assert max_jump <= 5_000


# ── Real-return and withdrawal-rate display logic ─────────────────────────────

class TestDisplayMetrics:
    def test_real_return_calculation(self):
        sp = {"mean_annual_return": 7.0, "inflation_rate": 3.0}
        real_return = sp["mean_annual_return"] - sp["inflation_rate"]
        assert real_return == pytest.approx(4.0)

    def test_withdrawal_rate_4pct_rule(self):
        net_from_portfolio = 80_000
        total_net_worth = 2_000_000
        wr = net_from_portfolio / total_net_worth * 100
        assert wr == pytest.approx(4.0)
        assert wr <= 4.0   # exactly at the rule

    def test_withdrawal_rate_above_4pct(self):
        net_from_portfolio = 100_000
        total_net_worth = 2_000_000
        wr = net_from_portfolio / total_net_worth * 100
        assert wr > 4.0


# ── End-to-end: full data flow through engine ─────────────────────────────────

class TestEndToEnd:
    def test_full_pipeline(self, portfolio_state, default_cash_flows, default_sim_params):
        """ETL output → SimulationParams → engine.run() → result dict."""
        from engine import SimulationParams
        from engine.monte_carlo import run as run_engine

        active = default_cash_flows[default_cash_flows["Active"]]
        expenses = float(active[active["Category"] != "Income"]["Annual ($)"].sum())
        income   = float(active[active["Category"] == "Income"]["Annual ($)"].sum())
        sp = default_sim_params

        params = SimulationParams.from_portfolio_state(
            portfolio_state,
            overrides={
                "annual_spending_today":     expenses,
                "social_security_annual":    income,
                "social_security_start_age": int(sp["social_security_start_age"]),
                "mean_annual_return":        sp["mean_annual_return"] / 100.0,
                "return_std_dev":            sp["return_std_dev"] / 100.0,
                "inflation_rate":            sp["inflation_rate"] / 100.0,
                "plan_to_age":               int(sp["plan_to_age"]),
                "num_iterations":            int(sp["num_iterations"]),
                "filing_status":             sp["filing_status"],
                "household_size":            int(sp["household_size"]),
            },
        )

        result = run_engine(params, config_dir=CONFIG_DIR, seed=42)

        # Structural checks
        assert "success_rate" in result
        assert "median_trajectory" in result
        assert "median_taxes" in result
        assert "median_healthcare" in result
        assert len(result["ages"]) == (sp["plan_to_age"] - int(params.current_age) + 1)

        # With $1.4M portfolio and $80k spending, should have reasonable success rate
        assert result["success_rate"] >= 0.0
        assert result["success_rate"] <= 1.0
